=== unerfahren/fun/src/main/resources/xsd/employee.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="people" type="people"/>
    <xs:element name="employee" type="employee"/>

    <xs:complexType name="employee">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string" minOccurs="0"/>
            <xs:element name="id" type="xs:int" minOccurs="0"/>
            <xs:element name="lastName" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="people">
        <xs:sequence maxOccurs="unbounded">
            <xs:element ref="employee"/>
        </xs:sequence>
    </xs:complexType>
<!--    <xs:complexType name="employee">-->
<!--        <xs:sequence>-->
<!--         <xs:element ref="department" minOccurs="0"/>&ndash;&gt;-->
<!--            <xs:element name="firstName" type="xs:string" minOccurs="0"/>-->
<!--            <xs:element name="id" type="xs:int" minOccurs="0"/>-->
<!--            <xs:element name="lastName" type="xs:string" minOccurs="0"/>-->
<!--        </xs:sequence>-->
<!--    </xs:complexType>-->


<!--        <xs:complexType name="department">-->
<!--            <xs:sequence>-->
<!--                <xs:element name="id" type="xs:int" minOccurs="0"/>-->
<!--                <xs:element name="name" type="xs:string" minOccurs="0"/>-->
<!--            </xs:sequence>-->
<!--        </xs:complexType>-->
</xs:schema>

=== unerfahren/fun/target/classes/employee.xml
<people  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="employee.xsd">
    <employee>
        <firstName>fafa</firstName>
        <id>123</id>
        <lastName>fafa</lastName>
    </employee>
    <employee>
        <firstName>fafa</firstName>
        <id>123</id>
        <lastName>fafa</lastName>
    </employee>
</people>
